# Welcome to Amplified for Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Caff(カフ)ー寂しさバイバイ。ワンタッチで、気の合う仲間と話せる会話アプリ。気になるあの人と話して、距離を縮めよう。相性の良い人と話して、新しい出会いを見つけよう。
og_title: Caff(カフ)ー寂しさバイバイ。ワンタッチで、気の合う仲間と話せる会話アプリ。気になるあの人と話して、距離を縮めよう。相性の良い人と話して、新しい出会いを見つけよう。
og_description: Caff(カフ)は、寂しいとき、ワンタッチで、気の合う仲間と話せる会話アプリ。気になるあの人と話して、距離を縮めよう。相性の良い人と話して、新しい出会いを見つけよう。
og_site_name: Caff
og_url: https://www.caff.co.jp
email: your-email@domain.com
description: >
  Caff(カフ)は、寂しいとき、ワンタッチで、気の合う仲間と話せる会話アプリ。気になるあの人と話して、距離を縮めよう。相性の良い人と話して、新しい出会いを見つけよう。
keywords: "Caff,カフ"
logo: "/assets/images/logo.png"
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://www.caff.co.jp" # the base hostname & protocol for your site
paginate:	5 # The number of posts to show per page on your homepage

name: 'Caff Inc.'
bio: >
  Mea suas vituperatoribus et, virtute corpora quaestio cum ut.
  Ne solet nostrum complectitur pri, vis ut inani populo.
author_image: "/assets/images/author.jpg"
twitter_username: jekyllrb
github_username:  jekyll

# Google Analytics
analytics_id: "UA-124723811-1"

# Build settings
markdown: kramdown

kramdown:
  parse_block_html: true

gems:
  - jekyll-paginate
