# Welcome to Amplified for Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Caff
email: your-email@domain.com
description: >
  今日も誰かとおしゃべりしよう
logo: "/assets/images/logo.jpg"
google-play-badge: "/assets/images/google-play-badge.png"
appstore-badge: "/assets/images/appstore-badge.png"
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://www.caff.co.jp" # the base hostname & protocol for your site
paginate:	5 # The number of posts to show per page on your homepage

name: 'Caff Inc.'
bio: >
  Mea suas vituperatoribus et, virtute corpora quaestio cum ut.
  Ne solet nostrum complectitur pri, vis ut inani populo.
author_image: "/assets/images/author.jpg"
twitter_username: jekyllrb
github_username:  jekyll

# Google Analytics
analytics_id: ""

# Build settings
markdown: kramdown

kramdown:
  parse_block_html: true

gems:
  - jekyll-paginate
